import { PUBLIC_SEO_FIXTURES } from "@/lib/public-seo/fixtures"
import { buildCanonicalUrl, buildRobotsConfig, buildSitemapEntries, listPublishedPublicPages } from "@/lib/public-seo/public-pages"
import type { ChangeFrequency } from "@/lib/domain/constants"
import type { PublicPlacePageRow } from "@/types/database"

const SITE_URL = "http://localhost:3000" as const

export type SitemapStatusCard = {
  readonly label: string
  readonly value: string
  readonly description: string
  readonly tone: "accent" | "neutral" | "warning"
}

export type AdminSitemapEntry = {
  readonly url: string
  readonly changeFrequency: ChangeFrequency
  readonly priority: number
  readonly lastModified: string
}

export type AdminSitemapStatus = {
  readonly source: "fixture" | "supabase"
  readonly sitemapUrl: string
  readonly robotsUrl: string
  readonly cards: readonly SitemapStatusCard[]
  readonly entries: readonly AdminSitemapEntry[]
  readonly disallowedPaths: readonly ["/admin", "/api", "/login", "/private"]
}

export interface AdminSitemapRepository {
  listPublishedPlacePages(): Promise<readonly PublicPlacePageRow[]>
}

export async function loadAdminSitemap(repository?: AdminSitemapRepository): Promise<AdminSitemapStatus> {
  const robotsConfig = buildRobotsConfig(SITE_URL)
  const robotsUrl = buildCanonicalUrl(SITE_URL, "/robots.txt")

  if (repository === undefined) {
    const publishedPages = listPublishedPublicPages(PUBLIC_SEO_FIXTURES)
    const entries = buildSitemapEntries(PUBLIC_SEO_FIXTURES, SITE_URL)
    return buildStatus({ source: "fixture", sitemapUrl: robotsConfig.sitemap, robotsUrl, entries, excludedCount: PUBLIC_SEO_FIXTURES.length - publishedPages.length })
  }

  const rows = await repository.listPublishedPlacePages()
  const entries = rows.map(publicViewRowToSitemapEntry)
  return buildStatus({ source: "supabase", sitemapUrl: robotsConfig.sitemap, robotsUrl, entries, excludedCount: 0 })
}

function buildStatus(input: Readonly<{ source: "fixture" | "supabase"; sitemapUrl: string; robotsUrl: string; entries: readonly AdminSitemapEntry[]; excludedCount: number }>): AdminSitemapStatus {
  return {
    source: input.source,
    sitemapUrl: input.sitemapUrl,
    robotsUrl: input.robotsUrl,
    cards: [
      { label: "Sitemap URL", value: input.sitemapUrl, description: "Generated by the public sitemap module from canonical public URLs.", tone: "accent" },
      { label: "Robots URL", value: input.robotsUrl, description: "Robots policy mirrors the public SEO module without external submission calls.", tone: "neutral" },
      { label: "Published URLs", value: String(input.entries.length), description: "Only published public records are included in the generated sitemap preview.", tone: "accent" },
      { label: "Excluded private/draft", value: String(input.excludedCount), description: "Draft records and private admin paths are excluded before rendering this status page.", tone: "warning" },
    ],
    entries: input.entries,
    disallowedPaths: ["/admin", "/api", "/login", "/private"],
  }
}

function publicViewRowToSitemapEntry(row: PublicPlacePageRow): AdminSitemapEntry {
  return {
    url: row.canonical_url ?? buildCanonicalUrl(SITE_URL, row.path),
    changeFrequency: row.change_frequency,
    priority: row.priority,
    lastModified: row.last_modified_at ?? "",
  }
}
