import type { PublicSeoRecord } from "./types"
import { GENERATED_FUNERAL_PUBLIC_PAGES } from "./funeral-seed"

export const DEFAULT_ORDER_URL = "https://팔도플라워.com" as const

export const PUBLIC_SEO_FIXTURES = [
  {
    id: "seo_area_1",
    type: "area",
    slug: "area-seoul-seocho",
    path: "/area/area-seoul-seocho",
    status: "published",
    title: "서울 서초구 근조화환 배송 안내",
    description: "서울 서초구 장례식장과 병원 근조화환 주문 안내입니다.",
    canonicalUrl: "https://seo.example.com/area/area-seoul-seocho",
    priority: 0.7,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: "서울 서초구",
    city: "서울",
    district: "서초구",
    address: null,
    homepage: null,
    ctaUrl: null,
    place: null,
    content: {
      faq: [{ question: "서초구 근조화환 주문은 어디로 하나요?", answer: "주문 CTA를 통해 팔도플라워로 이동합니다." }],
      keywords: ["서초구 근조화환", "장례식장 화환"],
      internalLinks: [{ href: "/funeral/funeral-seoul-seocho", label: "서초 장례식장" }],
    },
    privateSource: {
      email: "private@example.com",
      memo: "internal memo",
      imported_payload: { 이메일: "private@example.com", 메모: "internal memo" },
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
  {
    id: "seo_funeral_1",
    type: "funeral",
    slug: "funeral-seoul-seocho",
    path: "/funeral/funeral-seoul-seocho",
    status: "published",
    title: "서울 서초 장례식장 근조화환",
    description: "서울 서초 장례식장 근조화환 주문과 배송 안내입니다.",
    canonicalUrl: "https://seo.example.com/funeral/funeral-seoul-seocho",
    priority: 0.8,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: "서울 서초구",
    city: "서울",
    district: "서초구",
    address: "서울 서초구 반포대로 222",
    homepage: "https://funeral.example.com",
    ctaUrl: null,
    place: { name: "서울 서초 장례식장", category: "funeral", detailCategory: "전문장례식장" },
    content: {
      faq: [{ question: "장례식장으로 바로 배송되나요?", answer: "주문 페이지에서 배송 정보를 입력할 수 있습니다." }],
      keywords: ["서울 장례식장", "근조화환"],
      internalLinks: [{ href: "/area/area-seoul-seocho", label: "서초구 배송 안내" }],
    },
    privateSource: {
      email: "private@example.com",
      memo: "funeral memo",
      imported_payload: { 대표전화: "010-9999-0000" },
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
  {
    id: "seo_hospital_1",
    type: "hospital",
    slug: "hospital-busan-haeundae",
    path: "/hospital/hospital-busan-haeundae",
    status: "published",
    title: "부산 해운대 병원 근조화환",
    description: "부산 해운대 병원 장례 관련 근조화환 주문 안내입니다.",
    canonicalUrl: "https://seo.example.com/hospital/hospital-busan-haeundae",
    priority: 0.8,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: "부산 해운대구",
    city: "부산",
    district: "해운대구",
    address: "부산 해운대구 센텀중앙로 1",
    homepage: "https://hospital.example.com",
    ctaUrl: null,
    place: { name: "부산 해운대 병원", category: "hospital", detailCategory: "종합병원" },
    content: {
      faq: [{ question: "병원 장례식장 화환도 가능한가요?", answer: "주문 페이지에서 받는 곳을 지정할 수 있습니다." }],
      keywords: ["해운대 병원", "병원 근조화환"],
      internalLinks: [{ href: "/area/area-seoul-seocho", label: "지역 배송 안내" }],
    },
    privateSource: {
      email: "private@example.com",
      memo: "hospital memo",
      imported_payload: { 이메일: "private@example.com" },
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
  {
    id: "seo_product_1",
    type: "product",
    slug: "product-funeral-flower",
    path: "/products/product-funeral-flower",
    status: "published",
    title: "근조화환 상품 안내",
    description: "장례식장과 병원으로 보내는 근조화환 상품 안내입니다.",
    canonicalUrl: "https://seo.example.com/products/product-funeral-flower",
    priority: 0.6,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: null,
    city: null,
    district: null,
    address: null,
    homepage: null,
    ctaUrl: "https://팔도플라워.com/products/funeral-flower",
    place: null,
    content: {
      faq: [{ question: "상품 가격은 어디서 확인하나요?", answer: "주문 페이지에서 최신 상품 정보를 확인합니다." }],
      keywords: ["근조화환", "장례식장 화환"],
      internalLinks: [{ href: "/area/area-seoul-seocho", label: "지역별 배송 안내" }],
    },
    privateSource: {
      email: "private@example.com",
      memo: "product memo",
      imported_payload: null,
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
  {
    id: "seo_draft_1",
    type: "funeral",
    slug: "draft-funeral",
    path: "/funeral/draft-funeral",
    status: "draft",
    title: "Draft funeral",
    description: "Draft page",
    canonicalUrl: "https://seo.example.com/funeral/draft-funeral",
    priority: 0.5,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: null,
    city: null,
    district: null,
    address: null,
    homepage: null,
    ctaUrl: null,
    place: null,
    content: { faq: [], keywords: [], internalLinks: [] },
    privateSource: {
      email: "private@example.com",
      memo: "draft memo",
      imported_payload: null,
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
  {
    id: "seo_private_path_1",
    type: "area",
    slug: "admin-leak",
    path: "/admin/leak",
    status: "published",
    title: "Private path",
    description: "Must not be public",
    canonicalUrl: "https://seo.example.com/admin/leak",
    priority: 0.1,
    changeFrequency: "never",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: null,
    city: null,
    district: null,
    address: null,
    homepage: null,
    ctaUrl: null,
    place: null,
    content: { faq: [], keywords: [], internalLinks: [] },
    privateSource: {
      email: "private@example.com",
      memo: "private path memo",
      imported_payload: null,
      synced_at: "2026-07-03T01:00:00.000Z",
      service_role: "service_role_fixture_secret",
      phone: "010-9999-0000",
    },
  },
] as const satisfies readonly PublicSeoRecord[]

export const PUBLIC_SEO_RECORDS = [...PUBLIC_SEO_FIXTURES, ...GENERATED_FUNERAL_PUBLIC_PAGES] as const
