import type { PublicSeoRecord } from "./types"

const PLACE_PRIVATE_SOURCE = {
  email: "private@example.com",
  memo: "place memo",
  imported_payload: { 대표전화: "010-9999-0000" },
  synced_at: "2026-07-03T01:00:00.000Z",
  service_role: "service_role_fixture_secret",
  phone: "010-9999-0000",
} as const

const HIDDEN_PLACE_BASE = {
  type: "place",
  priority: 0.5,
  changeFrequency: "weekly",
  lastModifiedAt: "2026-07-03T00:00:00.000Z",
  region: "부산 해운대구",
  city: "부산",
  district: "해운대구",
  homepage: null,
  ctaUrl: null,
  place: { name: "Hidden place", category: "꽃집", detailCategory: null },
  content: { faq: [], keywords: [], internalLinks: [] },
  privateSource: PLACE_PRIVATE_SOURCE,
} as const

export const PLACE_PUBLIC_SEO_FIXTURES = [
  {
    id: "seo_place_1",
    type: "place",
    slug: "place-busan-haeundae-flower",
    path: "/places/place-busan-haeundae-flower",
    status: "published",
    title: "부산 해운대 꽃집 근조화환",
    description: "부산 해운대 꽃집 근조화환 주문과 배송 안내입니다.",
    canonicalUrl: "https://seo.example.com/places/place-busan-haeundae-flower",
    priority: 0.8,
    changeFrequency: "weekly",
    lastModifiedAt: "2026-07-03T00:00:00.000Z",
    region: "부산 해운대구",
    city: "부산",
    district: "해운대구",
    address: "부산 해운대구 센텀동로 99",
    homepage: "https://public-place.example.com",
    ctaUrl: null,
    place: { name: "부산 해운대 꽃집", category: "꽃집", detailCategory: "근조화환 전문" },
    content: {
      faq: [{ question: "해운대구 당일 배송이 가능한가요?", answer: "주문 페이지에서 배송 시간을 상담할 수 있습니다." }],
      keywords: ["해운대 꽃집", "근조화환"],
      internalLinks: [{ href: "/area/area-seoul-seocho", label: "해운대구 배송 안내" }],
    },
    privateSource: PLACE_PRIVATE_SOURCE,
  },
  {
    ...HIDDEN_PLACE_BASE,
    id: "seo_place_ready_1",
    slug: "place-ready-hidden",
    path: "/places/place-ready-hidden",
    status: "ready",
    title: "Ready hidden place",
    description: "Ready place must stay hidden",
    canonicalUrl: "https://seo.example.com/places/place-ready-hidden",
    address: "부산 해운대구 비공개로 1",
  },
  {
    ...HIDDEN_PLACE_BASE,
    id: "seo_place_draft_1",
    slug: "place-draft-hidden",
    path: "/places/place-draft-hidden",
    status: "draft",
    title: "Draft hidden place",
    description: "Draft place must stay hidden",
    canonicalUrl: "https://seo.example.com/places/place-draft-hidden",
    address: "부산 해운대구 비공개로 2",
  },
  {
    ...HIDDEN_PLACE_BASE,
    id: "seo_place_archived_1",
    slug: "place-archived-hidden",
    path: "/places/place-archived-hidden",
    status: "archived",
    title: "Archived hidden place",
    description: "Archived place must stay hidden",
    canonicalUrl: "https://seo.example.com/places/place-archived-hidden",
    changeFrequency: "never",
    address: "부산 해운대구 비공개로 3",
  },
] as const satisfies readonly PublicSeoRecord[]
